# config/meta.yml

meta_product_name: "Mettez les pieds sous la table"
meta_title: "Mettez les pieds sous la table - Votre plus belle devanture en une heure"
meta_description: "Mettez les pieds sous la table est une plateforme permettant aux jeunes chefs de se créer un site web moderne et joli à moindre coût et en minimum de temps."
meta_image: "ms-icon-310x310.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards